In [55]:
import pandas as pd

In [56]:
df= pd.read_csv(r"Data\World_ranking.csv")

In [57]:
df_definitivo= df[["FIFA_Rank", "Country"]]
df_definitivo=df_definitivo.rename(
    columns={
        "FIFA_Rank" :"Equipo",
        "Country": "Rating"
    }
)

In [58]:
df2= pd.read_csv(r"Data\wikipedia-iso-country-codes.csv")
df_tabla = df2[["English short name lower case","Alpha-2 code"]]
df_tabla= df_tabla.rename(
    columns={
        "English short name lower case": "Nombre",
        "Alpha-2 code" : "Codigo"
    }
)
df_tabla

              Nombre Codigo
0        Afghanistan     AF
1      Åland Islands     AX
2            Albania     AL
3            Algeria     DZ
4     American Samoa     AS
..               ...    ...
251  North Macedonia     NM
252  Northern Cyprus     NS
253          Curaçao     CW
254        Kurdistan     KD
255      South Sudan     SS

[256 rows x 2 columns]

In [59]:
df_final= pd.merge(
    df_definitivo,
    df_tabla,
    left_on="Equipo",
    right_on="Codigo",
    how="left"
)

df_final

    Equipo  Rating                    Nombre Codigo
0       ES    2165                     Spain     ES
1       AR    2113                 Argentina     AR
2       FR    2081                    France     FR
3       EN    2020                   England     EN
4       BR    1984                    Brazil     BR
..     ...     ...                       ...    ...
239     NU     496                      Niue     NU
240     MP     432  Northern Mariana Islands     MP
241     CC     422   Cocos (Keeling) Islands     CC
242     PW     402                     Palau     PW
243     AS     369            American Samoa     AS

[244 rows x 4 columns]

In [ ]:
lista= ["Nombre","Rating"]
df_final= df_final[lista]
df_final= df_final.rename(
    columns={
        "Nombre":"Equipo"
    }
)

In [67]:
df_final.to_csv(r"output\fifa_elo.csv", index=False)